# palette for widget of urwid
palette = [
    ('activeListBox', 'black', 'light red'),
    ('activeLineBox', 'light red', 'default'),
    ('normalListBox', 'default', 'default'),
    ('header', 'black', 'light gray'),
    ('header_text', 'light red', 'default'),
    ('normal', 'default', 'default'),
    ('selected', 'black', 'light cyan'),
    ('popup', 'black', 'light cyan'),
    ('popup_title', 'white', 'light cyan'),
    ('buttonPopup', 'dark magenta', 'default'),
    ('toolbar_button', 'black', 'light gray'),
    ('toolbar_button_focus', 'white', 'dark blue'),
    ('toolbar_button_flash', 'black', 'yellow'),
    ('ok_button_focus', 'white', 'dark blue'),
    ('ok_button', 'light cyan', 'black'),
    ('cancel_button_focus', 'white', 'dark red'),
    ('cancel_button', 'light red', 'black'),
    ('info_text', 'light red', 'black'),
    ('side_text', 'light green', 'black'),
    ('path_style', 'white', 'black'),
    ("status_text_black", 'black', 'light gray'),
    ("status_text_red", 'dark red', 'light gray'),
    ("status_text_blue", 'dark blue', 'light gray')
]